pipeline {
    agent any

    environment {
        IMAGE_NAME = "application-image"
        CONTAINER_NAME = "application-container"
        PORT = "8081"

        // 결과 메일을 전송할 메일을 Credential로 제공 (ex.'test1@test.com', 'test2@test.com')
        EMAIL_SEND_ADDRESS = credentials('EMAIL_SEND_ADDRESS')
    }

    stages {
        // Stage : 빌드와 테스트
        stage('Build & Test') {
            steps  {
                echo "Build and test start"
                bat "gradlew.bat clean build"
                echo "Build and test complete"
            }
        }

        // Stage : Docker 이미지 빌드
        stage('Build Docker Image') {
            steps {
                echo "Build Docker Image start"
                bat "docker build -t %IMAGE_NAME% -f %WORKSPACE%\\cicd\\Dockerfile %WORKSPACE%"
                echo "Build Docker Image complete"
            }
        }

        // Stage :  배포
        stage('Deploy') {
            steps {
                echo "Try remove ${CONTAINER_NAME} Container"

                bat """
                docker ps -a --filter "name=%CONTAINER_NAME%" --format "{{.Names}}" | findstr /i "%CONTAINER_NAME%" >nul
                IF %ERRORLEVEL% EQU 0 (
                    echo Stopping and removing existing container: %CONTAINER_NAME%
                    docker stop %CONTAINER_NAME%
                    docker rm %CONTAINER_NAME%
                ) ELSE (
                    echo No existing container named %CONTAINER_NAME% found.
                )
                exit 0
                """

                bat """
                docker run -d ^
                    -p %PORT%:%PORT% ^
                    --name %CONTAINER_NAME% ^
                    %IMAGE_NAME% ^
                """

                echo "Docker container ${CONTAINER_NAME} started."
            }

            // 결과를 이메일로 전송
            post {
                success { // 성공 메일 전송
                    mail to: "${env.EMAIL_SEND_ADDRESS}",
                    subject: "빌드 성공: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                    body: "빌드가 성공적으로 완료되었습니다!\n프로젝트: ${env.JOB_NAME}\n빌드 번호: ${env.BUILD_NUMBER}\n빌드 URL: ${env.BUILD_URL}"
                }
                failure { // 실패 메일 전송
                    mail to: "${env.EMAIL_SEND_ADDRESS}",
                    subject: "빌드 실패: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                    body: "빌드가 실패했습니다!\n프로젝트: ${env.JOB_NAME}\n빌드 번호: ${env.BUILD_NUMBER}\n빌드 URL: ${env.BUILD_URL}\n\n빌드 로그를 확인해주세요."
                }
            }
        }
    }
}
